[package]
name = "sm2-plus"
version = "0.2.0"
authors = ["Monte Johnston <johnston.monte@gmail.com>"]
license = "MIT/Apache-2.0"
description = """
A library for spaced repetion learning
"""

[dependencies]
